language: python

python:
  - "3.6"

install:
  - pip install mkdocs
  - pip install mkdocs-material==4.6.3
  - pip install pymdown-extensions==6.3
  - pip install mkdocs-git-committers-plugin
  - echo -e "machine github.com\n  login ${GITHUB_TOKEN}" > ~/.netrc

script:
  - mkdocs gh-deploy --force --clean
  - mkdocs build

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ];then mkdocs gh-deploy --force --clean; fi'

branches:
  only:
    - master