dist: focal
language: python

python:
  - "3.8"

install:
  - pip install mkdocs==1.2.3 mkdocs-material==4.6.3
  - pip install jinja2==3.0.3
  - pip install mkdocs-git-authors-plugin mkdocs-blogging-plugin
  - pip install mkdocs-git-revision-date-localized-plugin
  - echo -e "machine github.com\n login ${GITHUB_TOKEN}" > ~/.netrc

script:
  - mkdocs gh-deploy --force --clean
  - mkdocs build

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ];then mkdocs gh-deploy --force --clean; fi'

branches:
  only:
    - master