language: python

python:
  - "3.6"

install:
  - pip install mkdocs
  - pip install mkdocs-material==4.6.3
  - pip install pymdown-extensions==6.3
  - echo -e "machine github.com\n  login ${GITHUB_TOKEN}" > ~/.netrc

script:
  - mkdocs gh-deploy --force --clean
  - apt list --installed

branches:
  only:
    - master