name: Github Pages Deployment

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs-material==8.3.3 jinja2==3.0.3 mkdocs-git-authors-plugin mkdocs-blogging-plugin mkdocs-git-revision-date-localized-plugin
      - run: mkdocs gh-deploy --force